# Generated by Django 2.0 on 2018-07-27 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180727_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote_model',
            name='image_select',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
