# Generated by Django 2.0 on 2018-07-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_vote_model_image_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_model',
            name='image_select',
        ),
    ]
