# Generated by Django 2.0 on 2018-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180728_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_model',
            name='entrep',
            field=models.CharField(choices=[('mark zuckerberg', 'MARK ZUCKERBERG'), ('steve jobs', 'STEVE JOBS'), ('jack ma', 'JACK MA'), ('elon musk', 'ELON MUSK'), ('warren buffet', 'WARREN BUFFET')], default='Select Here.', max_length=15),
        ),
    ]
