# Generated by Django 2.0 on 2018-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20180728_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote_model',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
