# Generated by Django 2.0 on 2018-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_vote_model_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_model',
            name='entrep',
            field=models.CharField(choices=[('steve1.jpg', 'steve1'), ('steve2.jpg', 'steve2'), ('steve3.jpg', 'steve3')], default='Select Here.', max_length=15),
        ),
    ]
