# Generated by Django 2.0 on 2018-09-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180917_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user1',
            new_name='user',
        ),
    ]
