# Generated by Django 2.0 on 2018-09-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180917_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='user1',
        ),
    ]
