# Generated by Django 2.0 on 2018-09-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180917_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user1',
        ),
    ]
