# Generated by Django 2.0 on 2018-09-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
