# Generated by Django 2.0 on 2018-05-11 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180511_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='data',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
