# Generated by Django 2.0 on 2018-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_userprofileinfo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
