# Generated by Django 2.0 on 2018-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20180511_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='symbol',
            field=models.ImageField(blank=True, upload_to='symbols'),
        ),
    ]
