# Generated by Django 2.0 on 2018-05-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_userprofileinfo_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='symbol',
        ),
    ]
