# Generated by Django 2.0 on 2018-06-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_feed',
            name='comment',
            field=models.TextField(max_length=264),
        ),
    ]
