# Generated by Django 2.0 on 2018-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180604_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_feed',
            name='comment',
            field=models.CharField(max_length=264),
        ),
    ]
