# Generated by Django 2.0 on 2018-06-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180604_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_feed',
            old_name='comment',
            new_name='idea',
        ),
    ]
