# Generated by Django 2.0 on 2018-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180528_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=12, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
