# Generated by Django 2.0 on 2018-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180605_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_prod', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=264)),
                ('ph_no', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
