# Generated by Django 2.0 on 2018-06-05 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180605_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_model',
            name='city',
            field=models.CharField(default=datetime.datetime(2018, 6, 5, 16, 22, 26, 739681, tzinfo=utc), max_length=164),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy_model',
            name='country',
            field=models.CharField(default=datetime.datetime(2018, 6, 5, 16, 22, 43, 158165, tzinfo=utc), max_length=164),
            preserve_default=False,
        ),
    ]
