# Generated by Django 2.0 on 2018-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180605_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_model',
            name='address_line1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='buy_model',
            name='address_line2',
            field=models.CharField(max_length=150),
        ),
    ]
