# Generated by Django 2.0 on 2018-06-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180605_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_model',
            old_name='address_line1',
            new_name='address_Line1',
        ),
        migrations.RenameField(
            model_name='buy_model',
            old_name='address_line2',
            new_name='address_Line2',
        ),
    ]
