# Generated by Django 2.0 on 2018-06-06 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20180605_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=164)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=99)),
                ('repeat_Password', models.CharField(max_length=99)),
                ('saved', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
