# Generated by Django 2.0 on 2018-06-06 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_register_model_repeat_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='repeat_Password',
            field=models.CharField(default=django.utils.timezone.now, max_length=99),
            preserve_default=False,
        ),
    ]
