# Generated by Django 2.0 on 2018-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20180616_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1064)),
                ('image', models.ImageField(blank=True, upload_to='attach')),
            ],
        ),
    ]
