# Generated by Django 2.0 on 2018-06-04 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180604_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_feed',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=264),
            preserve_default=False,
        ),
    ]
