# Generated by Django 2.0 on 2018-06-05 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_buy_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_model',
            name='ph_no',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
