# Generated by Django 2.0 on 2018-06-05 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180605_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_model',
            name='address',
        ),
        migrations.AddField(
            model_name='buy_model',
            name='address_line1',
            field=models.TextField(default=datetime.datetime(2018, 6, 5, 16, 47, 52, 949811, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy_model',
            name='address_line2',
            field=models.TextField(default=datetime.datetime(2018, 6, 5, 16, 47, 58, 754402, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
