# Generated by Django 2.0 on 2018-06-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180605_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot_com',
            name='com_foo',
            field=models.CharField(max_length=264),
        ),
    ]
