# Generated by Django 2.0 on 2018-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180607_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_feed',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
