# Generated by Django 2.0 on 2018-06-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='user',
        ),
        migrations.DeleteModel(
            name='register_model',
        ),
    ]
